person:
  userName: lisi
# userName:"lisi \n haha" 控制台会输出换行
# userName:'lisi \n haha' 控制台会输出lisi \\n haha
  boss: true
  birth: 2021/1/7
  age: 20
  pet: {name:啊旺,weight:100}
  interests:
    - 打篮球
    - 跑步
  animal: [小猫,小狗,小鱼]
  score:
    小猫:
      first: 100
    小狗:
      second: 102
    小鱼:
      third: 103
  salarys:
    - 100.0
    - 200.0
  allPets:
    sick:
      - {name:小猫,weight:100}
      - name: 小狗
        weight: 102
    health: [{name:小鱼,weight:103}]
